/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/index`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/plugins/ecc-hooks`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/plugins/index`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/plugins/lib/changed-files-store`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/changed-files`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/check-coverage`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/format-code`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/git-summary`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/index`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/lint-check`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/run-tests`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/security-audit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orari` | `/orari`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/plugins/ecc-hooks`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/plugins/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/plugins/lib/changed-files-store`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/tools/changed-files`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/tools/check-coverage`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/tools/format-code`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/tools/git-summary`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/tools/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/tools/lint-check`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/tools/run-tests`; params?: Router.UnknownOutputParams; } | { pathname: `/../.opencode/tools/security-audit`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orari` | `/orari`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/../.opencode/index${`?${string}` | `#${string}` | ''}` | `/../.opencode/plugins/ecc-hooks${`?${string}` | `#${string}` | ''}` | `/../.opencode/plugins/index${`?${string}` | `#${string}` | ''}` | `/../.opencode/plugins/lib/changed-files-store${`?${string}` | `#${string}` | ''}` | `/../.opencode/tools/changed-files${`?${string}` | `#${string}` | ''}` | `/../.opencode/tools/check-coverage${`?${string}` | `#${string}` | ''}` | `/../.opencode/tools/format-code${`?${string}` | `#${string}` | ''}` | `/../.opencode/tools/git-summary${`?${string}` | `#${string}` | ''}` | `/../.opencode/tools/index${`?${string}` | `#${string}` | ''}` | `/../.opencode/tools/lint-check${`?${string}` | `#${string}` | ''}` | `/../.opencode/tools/run-tests${`?${string}` | `#${string}` | ''}` | `/../.opencode/tools/security-audit${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orari${`?${string}` | `#${string}` | ''}` | `/orari${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/index`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/plugins/ecc-hooks`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/plugins/index`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/plugins/lib/changed-files-store`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/changed-files`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/check-coverage`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/format-code`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/git-summary`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/index`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/lint-check`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/run-tests`; params?: Router.UnknownInputParams; } | { pathname: `/../.opencode/tools/security-audit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orari` | `/orari`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
